language: node_js
node_js:
- '9.4'
install:
  - npm install
  - ./node_modules/gitbook-cli/bin/gitbook.js install
script:
  - ./node_modules/gitbook-summary/bin/summary.js sm -t C3S -i node_modules
  - ./node_modules/gitbook-cli/bin/gitbook.js build . docs/
deploy:
  provider: pages
  skip_cleanup: true
  allow_empty_commit: true
  commiter-from-gh: true
  keep_history: false
  github_token: $GH_TOKEN
  local_dir: docs
